### PR TITLE
Added Seren as a search provider

### PR DESCRIPTION
**Pull request by Goldenfreddy0703**
Hey there,

I wanted to drop you a note or pr to express how impressed I am with your skin. It's not only fast and simple to navigate, but it's also downright amazing. Using it brings back fond memories of the old OSMC Skin, which I liked.

I took the liberty of integrating Seren as a search provider into your skin. However, I encountered a slight snag when attempting to add search paths for Actors/Actresses in both movies and TV shows. Unfortunately, it seems that Seren doesn't provide this feature at the moment.

Feel free to merge or close this pull request as you see fit. Looking ahead, perhaps we could explore integrating tmdb helper in the future. Just a thought!

Once again, kudos on creating such a fentastic skin and thank you for making this amazing skin!!!!

### CODE REVIEW

**Comment by umbrellaplug** [comment]
Fair warning. I have had terrible experiences with accepting commits from this person in the past. I strongly advise not to merge anything submitted by this username.

**Comment by Goldenfreddy0703** [comment]
> Fair warning. I have had terrible experiences with accepting commits from this person in the past. I strongly advise not to merge anything submitted by this username.

Little bit rude of you to say but whats in the past was the past and i have made mistakes in my life when i first started. @umbrellaplug when i was working with you, i didn't even know how to make a PR.  I've since grown and improved, and I'm committed to delivering better moving forward. Again, @umbrellaplug for the 3rd time, i am sorry for my mistakes when working with you, like i said, your a great developer and i don't mean to undermine your work or expertise in any way. Let's move forward positively, learn from past experiences, and strive for better collaboration in the future.

oh btw, this maybe off topic but if you blocked me on discord, i sent you a response on a topic about a retropie box you made and you were disappointed they packaged kodi 18 with it. Try Batocera, I have an arcade with it and it's been really great and it comes with the latest version of kodi. Anyway hope that helps.

**Comment by Goldenfreddy0703** [comment]
Oh yeah, I just thought it would be a good idea to add but if the dev rejects it, it's totally fine. 

Skin hasn't been updated in 3 months so why not take the opportunity to make a pr for it. 

I recently tried this skin for the first time and it's great. It's fast, minimal, and easy to work with. Only 2 downside I do see with it is just lack of search functionality which is ok and maybe extended info but other then that, it's a great skin.

**Comment by Omarscomin** [comment]
>Looking ahead, perhaps we could explore integrating tmdb helper in the future.

This made me laugh so hard that I spit my drink out

**Comment by Goldenfreddy0703** [comment]
> This made me laugh so hard that I spit my drink out

Hehe yeah I just thought of that. 😂

if this skin isn't really made for tmdb helper and mostly made for fen or fenlight. It's quite understandable sense it's called Fentastic after all.

**Comment by ivarbrandt** [comment]
I'm glad you're enjoying it!

I won't be accepting this PR for a few reasons:

1. I have currently paused active development of FENtastic until a stable release of Omega becomes available.
2. I don't feel comfortable accepting PRs. I like to see the effects of my changes to the code base and I feel it is harder to do that when accepting PRs. In your case it's not a whole lot of code but you get my drift.
3. The code you provided is incomplete. I can let you know which parts are missing if you'd like.

As for adding TMDbHelper, thank you for the offer but I will be also declining this as well. In my experience TMDbHelper is very resource intensive. This is fine for PCs and other powerful devices but for everyone else is left with a skin that lags, isn't smooth, and/or crashes their device. This goes against my core philosophy when creating skins. Regardless of the functionality added with TMDbHelper, it would make my skin inaccessible for people with less powerful devices and I'm not cool with that.

Once again, thank you for the kind words and I'm really happy that you are enjoying the skin :)

**Comment by Goldenfreddy0703** [comment]
Hey, thank you for getting back to me! I really appreciate your reply. I understand your concerns about Seren and TMDB Helper. I also found Seren a bit uncertain because it lacks a search result history for actors and does not have a search for Trakt lists. And yes, TMDB Helper can be sluggish, especially with skins such as Arctic Fuze or Arctic Horizon or Artic Zypher maybe.

You mentioned the code I provided for Seren was incomplete. I would greatly appreciate it if you could point out what parts I missed. Understanding this would help me improve and maybe even create my own version of the skin in the future.

It's great to hear that you're still working on enhancing the skin. Your dedication to improving it is truly commendable. I'm excited to see the updates you bring to your skin. If there's anything I can do to support your efforts, please let me know. Keep up the fentastic work!

Again, Thank you very much

**Comment by ivarbrandt** [comment]
I made a mistake. Upon closer inspection you did provide all the necessary code. I haven't added it yet to the skin but it does look correct. I thought that you were missing the visibility conditions in `SkinSettings.xml` but since you are only adding Movies and TV Shows widgets for Seren then those aren't necessary as those widgets are used for all providers. Same goes for the actual widgets in the `Custom_1121_SearchResults.xml` window. I apologize for my oversight.

The process is similar for adding in Actors/Actresses or Keywords. You may have to create a new variable or two and set the conditions to the appropriate skin strings. Same is true for TRAKT Lists that use the stacked widgets.

Also, this is optional but you can also add in the path for TRAKT lists (if available in Seren) to the TRAKT button in the search window if you'd like. On line 736 in `Variables.xml` you would add another value:

```
<variable name="TRAKTButtonActionsVar">
  <value condition="String.IsEqual(Skin.String(current_search_provider),0)">ActivateWindow(10025,plugin://plugin.video.fen/?&amp;mode=navigator.trakt_lists,return)</value>
  <value condition="String.IsEqual(Skin.String(current_search_provider),1)">ActivateWindow(10025,plugin://plugin.video.fenlight/?&amp;mode=navigator.my_content&amp;name=My%20Lists,return)</value>
  <value condition="String.IsEqual(Skin.String(current_search_provider),2)">ActivateWindow(10025,plugin://plugin.video.umbrella/?action=trakt_Navigator,return)</value>
  <value>ActivateWindow(10025,plugin://plugin.video.fen/?&amp;mode=navigator.trakt_lists,return)</value>
</variable>
```

If you have other questions or run into any issues feel free to reach out.

**Comment by Goldenfreddy0703** [comment]
Awesome and that's ok, when i was looking on the other addons like how the umbrella search was configured and fen and fenlight was, i was sure i got all the necessary stuff but i wasn't sure due to the Custom_1121_SearchResults.xml and SkinSettings.xml.

Thank you for looking over my code again on that and again, its totally fine. 
Thank you!!!

**Pull request closed without merging**
